project_id = "obtvqplaazunsoowajrp"

[functions.generate-thumbnail]
verify_jwt = false

[functions.generate-titles]
verify_jwt = false

[functions.face-swap]
verify_jwt = false

[functions.edit-thumbnail]
verify_jwt = false

[functions.upload-to-cloudinary]
verify_jwt = false

[functions.analyze-youtube]
verify_jwt = false

[functions.score-thumbnail]
verify_jwt = false

[functions.ab-test-thumbnails]
verify_jwt = false

[functions.generate-from-youtube]
verify_jwt = false
